### ISSUE TITLE
Research Seamlessdocs - a form front end

### ISSUE THREAD

**Issue by GBirch** [GBirch/massforms8#29]
- [ ] Meet with Josh Gee, from City of Boston, who is working to digitize forms via SeamlessDocs (Tuesday, August 30th, 10am - 11am in Fenway Conference Room)

**Comment by GBirch** [comment]
If it appears it can work, we should review with the product manager for the Boston website for their experiences.

**Comment by weitzman** [comment]
Met with Josh. He is using Seamless as a web form builder. Not using their fancy product which has users filling in PDFs. He has focused purely on end user digitization and he doesn't touch workflow at all. He emails PDF submissions and stores them in client's Google drive.

Overall, this product is a bit less functional than form.io. It looks good though.
