### ISSUE TITLE
Configure Acquia demo site with Acquia pipelines

### ISSUE THREAD

**Issue by GBirch** [GBirch/massforms8#31]
https://docs.acquia.com/pipelines

mf8@svn-5842.devcloud.hosting.acquia.com:mf8.git

https://insight.acquia.com/cloud/workflow?s=3728516

**Comment by GBirch** [comment]
Dev env URL:  http://mf8ryjdnclyfu.devcloud.acquia-sites.com/AH_VIEW

Staging env URL:  http://mf8w2futneyk5.devcloud.acquia-sites.com/AH_VIEW

**Comment by weitzman** [comment]
I requested access to Private Beta.

**Comment by weitzman** [comment]
Re-pinged him today.

**Comment by weitzman** [comment]
We now have Pipeline access. I'm working on setting it up this week.

**Comment by GBirch** [comment]
Before we can call this done, at least one of GIles/Isaac/Rob needs to be able to deploy to the site and run pipeline.
